### ISSUE TITLE
Query error with parameterised queries

### ISSUE THREAD

**Issue by craigfrancis** [staabm/phpstan-dba#106]
Following up on [Issue 69](https://github.com/staabm/phpstan-dba/issues/69), as this is a different issue (I don't want to mix up the two things).

The SQL error, when checking `$pdo->prepare()`:

    ------ ------------------------------------------------------------------ 
     Line   index.php                                                         
    ------ ------------------------------------------------------------------ 
     5      Query error: You have an error in your SQL syntax; check the      
            manual that corresponds to your MySQL/MariaDB server version for  
            the right syntax to use near ':id AND 2=2 LIMIT 0' at line 1      
                                                                              
            Simulated query: SELECT * FROM user WHERE id = :id AND 2=2 LIMIT  
            0 (1064).                                                         
     8      Query error: You have an error in your SQL syntax; check the      
            manual that corresponds to your MySQL/MariaDB server version for  
            the right syntax to use near '? AND 2=2 LIMIT 0' at line 1        
                                                                              
            Simulated query: SELECT * FROM user WHERE id = ? AND 2=2 LIMIT 0  
            (1064).                                                           
    ------ ------------------------------------------------------------------

This output used the new debug mode in `RuntimeConfiguration` (thanks for adding).

It's happening on both named and question mark parameter queries.

The `MysqliQueryReflector::simulateQuery()` method is used, and it looks like the query is being [sent to the database](https://github.com/staabm/phpstan-dba/blob/909ec0048eea8e8affb948226179f385a41fff39/src/QueryReflection/MysqliQueryReflector.php#L157) without parameters being provided (or replaced).

It's interesting that later, when `$stmt->execute()` is being tested, the values are being replaced in `QueryReflection::replaceParameters()`.

I wonder if this check can be done during `$stmt->execute()`, when you have some parameters to use... or it might be possible to generate some values, even if it's the number 0, or a value that's appropriate for the field type (considering it's not actually returning any records with a `LIMIT 0`).

**Comment by staabm** [comment]
for some reason the placeholder replacement does not work on your machine.
I cannot reproduce either in CI nor on my windows laptop.

could you dig a bit thru 

https://github.com/staabm/phpstan-dba/blob/2eaf50b19e185def9eeabe3cfa6e1171a5271015/src/QueryReflection/QueryReflection.php#L134-L166

to get a feeling why it fails in your setup?

**Comment by staabm** [comment]
I was able to reproduce this problem, when 

```
    -
        class: staabm\PHPStanDba\Rules\SyntaxErrorInQueryMethodRule
        tags: [phpstan.rules.rule]
        arguments:
            classMethods:
                - 'rex_sql::setQuery#0'
                - 'rex_sql::setDBQuery#0'
                
```

is configurated for a method, which actually takes a prepared statement and query-string separately

**Comment by craigfrancis** [comment]
I think we are on the same page... and Pull Request 119 has stopped the error.

From my understanding, the checking of `$pdo->prepare()` does not call `replaceParameters()`, so the SQL is sent to the database with the placeholders (causing it to error).

In comparison `$stmt->execute()` (which is checked after this error has happened), does use `replaceParameters()`, and is fine.

I'm just wondering, could the parameters simply be replaced with the number 0? something like this:

```php
$queryString = preg_replace('/(\?|\b:[a-zA-Z0-9_]+\b)/', '0', $queryString);
```

It's already using `LIMIT 0`, so it won't return any records... but I must confess I've not really checked it, and this approach might cause other issues.

e.g. While these are a bit contrived, `WHERE question LIKE "%?"` or `WHERE meta_data LIKE "%:tag_name%"`. Because I'm not really doing proper parsing of the SQL string, those characters would be incorrectly replaced because they look like placeholders.

As an aside, I think there might have a similar issue with `countPlaceholders()` and `extractNamedPlaceholders()`.

I wonder, if this is a problem, does it needs to do something similar to the [pdo_parse_params()](https://github.com/php/php-src/blob/944b6b6bbd6f05ad905f5f4ad07445792bee4027/ext/pdo/pdo_sql_parser.re#L82) function, rather than simply using the [BINDCHR](https://github.com/php/php-src/blob/944b6b6bbd6f05ad905f5f4ad07445792bee4027/ext/pdo/pdo_sql_parser.re#L48) regex (used later as `PDO_PARSER_BIND`)... as that supports escaped question marks (`??`), comments (`/* What about X? */` or `-- To fix?`), and quoted string values (if I'm reading this correctly, using `ANYNOEOF`?).

**Comment by staabm** [comment]
You are right that the current parsing is a bit naive and can easily break in edge cases.

Regarding your inital problem: I guess your phpstan-dba config is wrongly mixing `SyntaxErrorInPreparedStatementMethodRule` and `SyntaxErrorInQueryMethodRule`.

**Comment by craigfrancis** [comment]
Just running a quick test (need to go in a bit)... I've used a script that only contains:

```php
<?php

$pdo = new PDO('mysql:dbname=test;host=localhost', 'test', 'test', [PDO::ATTR_EMULATE_PREPARES => false]);

$stmt = $pdo->prepare('SELECT * FROM user WHERE id = ?');
```

And that triggered the 'Query error' in `SyntaxErrorInQueryMethodRule`.

Taking a guess, that might be due to the provided [dba.neon](https://github.com/staabm/phpstan-dba/blob/main/config/dba.neon#L26) file.

**Comment by staabm** [comment]
> Just running a quick test (need to go in a bit)... I've used a script that only contains:
> 
> ```
> <?php
> 
> $pdo = new PDO('mysql:dbname=test;host=localhost', 'test', 'test', [PDO::ATTR_EMULATE_PREPARES => false]);
> 
> $stmt = $pdo->prepare('SELECT * FROM user WHERE id = ?');
> ```
> 
> And that triggered the 'Query error' in `SyntaxErrorInQueryMethodRule`.
> 
> Taking a guess, that might be due to the provided [dba.neon](https://github.com/staabm/phpstan-dba/blob/main/config/dba.neon#L26) file.

I think this example works on latest master. I think it was fixed with https://github.com/staabm/phpstan-dba/pull/119

at least running your example in a unit test seems to not produce a error, see https://github.com/staabm/phpstan-dba/pull/124

**Comment by craigfrancis** [comment]
Yep, when I used #119, that fixed the error... and I suspect those checks are run when it get's to the `$stmt->execute()` (sorry, gtg, and I'm probably not going to be available for a few days).

**Comment by staabm** [comment]
Does the initial issue still reproduce or can we close the issue?

**Comment by craigfrancis** [comment]
Yes, thank you (once I realised that composer was not updating).
