### ISSUE TITLE
Prepared statements with camelCased named placeholders

### ISSUE THREAD

**Issue by Seldaek** [staabm/phpstan-dba#109]
Not sure if related to another of the open issues tbh, but I tried this as it's IMO very promising and had to go around Doctrine DBAL for now to test it out but I got a rather unexpected result:

```
        $sql = '
            SELECT v.normalizedVersion, d.data
            FROM package_version v
            INNER JOIN download d ON d.id=v.id AND d.type = :versionType
            WHERE v.package_id = :package AND v.development = 0 AND v.normalizedVersion LIKE :majorVersion
        ';

        /** @var \Doctrine\DBAL\Driver\PDO\Connection $pdo */
        $pdo = $this->getEntityManager()->getConnection()->getWrappedConnection();
        $stmt = $pdo->prepare($sql);
        $stmt->execute(['package' => $package->getId(), 'versionType' => Download::TYPE_VERSION, 'majorVersion' => $majorVersion . '.%']);

        $result = $stmt->fetchAll(PDO::FETCH_ASSOC);
```

Line 37 is the `execute` call.
```
  37     Query expects placeholder :major, but it is missing from values given to execute().
  37     Query expects placeholder :version, but it is missing from values given to execute().
  37     Value :majorVersion is given to execute(), but the query does not contain this placeholder.
  37     Value :versionType is given to execute(), but the query does not contain this placeholder.
```

I have no idea why the placeholders `:majorVersion`/`:versionType` became `:major`/`:version`. It looks like it stopped parsing as soon as it encountered a capital letter, so it smells to me of a regex that's not case insensitive or something.. But I couldn't find anything in the code.

**Comment by staabm** [comment]
you are right.. capitel letter are the source of all evil ;-).

bug is here: https://github.com/staabm/phpstan-dba/blob/909ec0048eea8e8affb948226179f385a41fff39/src/Rules/PdoStatementExecuteMethodRule.php#L171

which chars are allowed in placeholder-names?

**Comment by staabm** [comment]
> to go around Doctrine DBAL for now

btw .. doctrine dbal support should be possible, see https://github.com/staabm/phpstan-dba/issues/94

**Comment by Seldaek** [comment]
Yeah I subscribed to that. I won't have time to implement that I believe, too involved for my phpstan-skills :) But definitely would be cool, as it's a fairly thin wrapper around PDO/PDOStatement, and it's the most useful doctrine integration IMO as query-builder stuff often returns real entities/objects (at least in my usage, YMMV), which is already easy to type correctly, and has less chances of mistakes in queries.

**Comment by staabm** [comment]
> has less chances of mistakes in queries.

one plus of phpstan-dba I learned in hindsight is, that it checks your query against your real schema in the db.
this means e.g. that you also have kind-of-coverage for your database migrations, since the analysis starts to fail, if you forget to commit your migration recipe.
