### ISSUE TITLE
Internal errors with array parameters

### ISSUE THREAD

**Issue by Seldaek** [staabm/phpstan-dba#156]
This code here makes PHPStan crash with this extension enabled:

```
    Internal error: Internal error: Unexpected expression type PHPStan\Type\ArrayType in file /var/www/packagist/src/Command/IndexPackagesCommand.php
     Run PHPStan with --debug option and post the stack trace to:
     https://github.com/phpstan/phpstan/issues/new?template=Bug_report.md
     Child process error (exit code 1):
```

https://github.com/composer/packagist/blob/e3f76f42980e6477e453f13526e33ed174318ff2/src/Command/IndexPackagesCommand.php#L292-L311

It seems to be due to the `Connection::PARAM_INT_ARRAY` usage, and the  fact that one of the parameters is an array, which I assume this lib isn't expecting yet.

**Comment by staabm** [comment]
https://github.com/staabm/phpstan-dba/pull/152 Fixed some array handling today.. 

Which version of phpstan-dba do you work with?

**Comment by Seldaek** [comment]
0.2.1

**Comment by staabm** [comment]
Reproduced in https://github.com/staabm/phpstan-dba/pull/158

will need some handling for generic array. This from #152 only worked for constant arrays.
