### ISSUE TITLE
demo: custom sql based database access layer

### ISSUE THREAD

**Issue by voku** [staabm/phpstan-dba#163]
There was somewhere already a demo implementation for zf1, or? 🤔

PS: thanks for pushing this code checks and for take care of code quality for us all 👌

**Comment by voku** [comment]
We use a simple wrapper around mysqli at work, so I wanted to figure out how to analyse it.

**Comment by staabm** [comment]
the [readme describes](https://github.com/staabm/phpstan-dba#use-syntaxerrorinpreparedstatementmethodrule-for-your-custom-classes) how you can register the built-in rules for your custom classes in .

see [dba.neon](https://github.com/staabm/phpstan-dba/blob/ed42d9c057ec6665d2be665b17862d1393e7c54c/config/dba.neon#L7-L37) for examples on how this is achieved for the builtin-in covered apis

**Comment by voku** [comment]
Can I also define a abstract class / method for the build-in rules?

**Comment by staabm** [comment]
Atm you need to define the method which actually is called

**Comment by staabm** [comment]
Said differently: i guess it would work also for a abstract method, when the type of your object is of the abstract class which defines said method

(Untested)

**Comment by staabm** [comment]
Did it work for you?

**Comment by voku** [comment]
Sorry I can't test anything the next days / weeks, I am still in the hospital with my little girl: https://twitter.com/suckup_de/status/1483871109393141768
