### ISSUE TITLE
Using stringable object as query parameter fails 

### ISSUE THREAD

**Issue by janedbal** [staabm/phpstan-dba#203]
```php
$dbalConnection->fetchAssociative('
    SELECT *
    FROM bar
    WHERE foo = :enum
', [
    'enum' => new Enum('foo'),
]);
```
Causes error:

> Uncaught staabm\PHPStanDba\DbaException: Unexpected expression type PHPStan\Type\ObjectType in /app/vendor/staabm/phpstan-dba/src/QueryReflection/QuerySimulation.php:91

Even though the **Enum has __toString** method which works fine in dbal query.

**Comment by staabm** [comment]
thx for reporting. this is obviously a bug and should work.

**Comment by staabm** [comment]
Atm we are php8+ only, so we could utilize the stringable interface
https://www.php.net/manual/en/class.stringable.php

for the impl we need a new instance-of check here
https://github.com/staabm/phpstan-dba/blob/4d1c84b2dd4241ab9aee1f8e111a84e9d1df6313/src/QueryReflection/QuerySimulation.php#L30

Testcase can be added at the bottom of https://github.com/staabm/phpstan-dba/blob/main/tests/data/pdo-prepare.php
