### ISSUE TITLE
Pls add Doctrine connection example to Readme

### ISSUE THREAD

**Issue by palansher** [staabm/phpstan-dba#204]
Hello!

> // TODO: Put your database credentials here
>         new MysqliQueryReflector(new mysqli('hostname', 'username', 'password', 'database'))
> 

I have no idea how to connect Doctrine/Dblal.
Please advise.

**Comment by staabm** [comment]
I am not sure what you are asking. you should put your database access credentials in this line.

**Comment by staabm** [comment]
yep its all you need todo atm. there are no doctrine specifics.



> the use of MySQL only is supposed in this example

atm phpstan-dba only supports mysqli/mariadb
