### ISSUE TITLE
Doctrina/dbal 2.x compat

### ISSUE THREAD

**Issue by staabm** [staabm/phpstan-dba#206]
See https://github.com/doctrine/dbal/blob/3.3.x/UPGRADE.md#deprecated-fetchmode-and-the-corresponding-methods

for newer 2.x releases some api is the same to 3.x.

its only about the low hanging fruit. I guess we mostly need to check places like
https://github.com/staabm/phpstan-dba/blob/4d1c84b2dd4241ab9aee1f8e111a84e9d1df6313/src/Extensions/DoctrineConnectionExecuteQueryDynamicReturnTypeExtension.php#L53

And see whether the checked version also satisfies doctrina dbal 2.x

**Comment by staabm** [comment]
@mitelg in case you are interessted in doctrine/dbal 2.x compat, you might invest some time and adjust the version checks in the [doctrine-extensions](https://github.com/staabm/phpstan-dba/tree/main/src/Extensions) where dbal 2.x is api compatibel with dbal 3.x

**Comment by mitelg** [comment]
I cannot promise anything, but maybe I will find some time :slightly_smiling_face:
