### ISSUE TITLE
Queries ending with semicolon failing simulation

### ISSUE THREAD

**Issue by janedbal** [staabm/phpstan-dba#213]
The query [simulation](https://github.com/staabm/phpstan-dba/blob/f365f068a3ba206926c4ff95f5cbd7553492b62c/src/QueryReflection/QuerySimulation.php#L101) causes analysis of queries with `;` at the end to fail on 

`Query error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL/MariaDB server version for the right syntax to use near 'LIMIT 0' at line 6 (1064).`

```mysql
SELECT foo
FROM bar;
```

**Comment by staabm** [comment]
thx for the report. which version of phpstan-dba do you use?

I fixed this problem a few releases ago.

**Comment by janedbal** [comment]
Sorry, my bad, I was using 0.2.6

**Comment by staabm** [comment]
no worries. in case you can still reproduce on the latest version, please provide a smal usage example which reproduces the problem
