### ISSUE TITLE
Return type for integers should be numeric-string 

### ISSUE THREAD

**Issue by Seldaek** [staabm/phpstan-dba#222]
This code here:

```
        $result = $this->getEntityManager()->getConnection()->fetchOne('SELECT verified FROM vendor WHERE name = :vendor', ['vendor' => $vendor]);

        return $result === '1';
```

Triggered:

```
Strict comparison using === between int<-128, 127> and '1' will always evaluate to false.
```

At least with doctrine connection like this it appears to really return `'1'`. I am not sure if there are cases where PDO will return the proper integers, or perhaps with Doctrine when using query builder it may have smarter return values. Would need to all be verified.

**Comment by Seldaek** [comment]
Now the sad thing with numeric-string is we lose the integer ranges :)

**Comment by staabm** [comment]
yeah, I guess this would only work as a big union of all possible values (and this is limited to at max 256 possible unique values)

**Comment by Seldaek** [comment]
Yeah that or you'd need numeric-string<x,y> syntax support in phpstan. That would be better but not sure it's worth it.

**Comment by staabm** [comment]
per https://stackoverflow.com/a/20123337 it should be possible using regular int etc

**Comment by Seldaek** [comment]
Hmm ok.. need to check the real runtime output I get,  maybe my code is broken :D

**Comment by Seldaek** [comment]
OK confirming I get `'1'` (string) back from a tinyint(1) column

**Comment by staabm** [comment]
Thanks for investigating. Thats great news. 

We will have a new RuntimeConfiguration switch then, with which you can tell phpstan-dba how types should be handled

https://github.com/staabm/phpstan-dba/blob/main/src/QueryReflection/RuntimeConfiguration.php

**Comment by Seldaek** [comment]
Also note that I just noticed this only says PDO MySQL in the PHP changelog. It may not apply to other DBs.

**Comment by staabm** [comment]
https://github.com/php/php-src/commit/c18b1aea289e8ed6edb3f6e6a135018976a034c6 also mentions a `ATTR_STRINGIFY_FETCHES` option.. did you try that? maybe that works without the problems of `ATTR_EMULATE_PREPARES`

**Comment by Seldaek** [comment]
I did try, it said it is not available for mysqlnd..

**Comment by staabm** [comment]
just landed a new `stringify` RuntimeConfiguration option: 

https://github.com/staabm/phpstan-dba#runtime-configuration

**Comment by Seldaek** [comment]
Great thanks, seems to work fine :)
