### ISSUE TITLE
Add support for SUM() & similar functions

### ISSUE THREAD

**Issue by Seldaek** [staabm/phpstan-dba#223]
SUM() can return `numeric-string|null` in mysql for example. Right now it is seen as mixed.

**Comment by staabm** [comment]
it should work, see https://github.com/staabm/phpstan-dba/blob/cbe8452082b73fe7eba4200d2e2f0a7543daa50d/tests/data/pdo.php#L157-L160

how can the count be `null`

**Comment by Seldaek** [comment]
Ah I see, probably didn't work because it's in a dynamically  generated query :) https://github.com/composer/packagist/blob/bd2a83835b2eed466b598dbb1cccd7e94b281f57/src/Entity/PhpStatRepository.php#L226-L234

As for null, docs say `Returns the sum of expr. If the return set has no rows, SUM() returns NULL.`

**Comment by staabm** [comment]
ok. need to test whether PHP does also return NULL or turns it into a zero

**Comment by staabm** [comment]
if you find a repro of this problem, I could investigate. closing until its reproducible.
