### ISSUE TITLE
Strange DBAL discrepancy between local env and CI

### ISSUE THREAD

**Issue by Seldaek** [staabm/phpstan-dba#225]
With this code here https://github.com/composer/packagist/blob/8a3d28e42f9790dea401e5f9afc7c2c9780b58d8/src/Entity/PackageRepository.php#L255-L270

Running locally I get:

> Method App\Entity\PackageRepository::getStalePackagesForDumping() should return array<int, string> but returns array<int<0, max>, int<0, 4294967295>>.

Which makes sense given #222

But on CI e.g. https://github.com/composer/packagist/runs/5037284175?check_suite_focus=true I get this:

> Method App\Entity\PackageRepository::getStalePackagesForDumping() should return array<int, string> but returns array<int, mixed>.

Any clue what could cause this? All dependency versions are the same as it installs from lock file.

**Comment by staabm** [comment]
having a mixed only for a single column-type would mean you are running into this case:
https://github.com/staabm/phpstan-dba/blob/e2939f28cb3e2b8cc465c15e78b965eade5b11c3/src/QueryReflection/MysqliQueryReflector.php#L293

are you sure you are using the same db schema locally and in CI?
maybe its a difference in mysql versions or maria db vs. mysql?

**Comment by Seldaek** [comment]
The package table has a simple int(11) primary id, nothing weird, and it definitely hasn't changed in 10 years so I believe my local schema matches CI :) 

https://github.com/composer/packagist/blob/8a3d28e42f9790dea401e5f9afc7c2c9780b58d8/src/Entity/Package.php#L62-L67

I'm on mysql8.0.13 and GH is on 8.0.26 but I doubt that'd make a difference here.. I can try to upgrade to be sure, wouldn't hurt anyway ;)

**Comment by staabm** [comment]
If time allows I can debug the CI job and the used phpstan-dba version within the CI pipeline.

**Comment by Seldaek** [comment]
On 8.0.28 locally now, still can't repro :/

**Comment by Seldaek** [comment]
Very confused, just tried again to run phpstan and suddenly it changed to the same output as CI?! 

I even tried clearing PHPStan & phpstan-dba caches earlier, it didn't help.. proper WTF here.. but at least it works now so I guess closing 🤷‍♂️

**Comment by staabm** [comment]
hm ok, so you are now able to debug locally why its returning `mixed`?

running phpstan with `--debug` disables all caches.. thats the first thing I try when caching might be a problem.

**Comment by staabm** [comment]
I have a new theory, why you get a `array<int, mixed>`,..

doctrine defines the method `fetchFirstColumn` on `Connection` to return `list<mixed>`:
https://github.com/doctrine/dbal/blob/0dc504e80b400870d4d1d0392394164b4dd39019/src/Connection.php#L888-L902

in your example phpstan-dba is taking one of the `return $defaultReturn` branches and therefore defines the return-type to whether doctrine-dbal itself defines at the phpdoc level

https://github.com/staabm/phpstan-dba/blob/47c99358abe46665d5228589209dd39cf3612d45/src/Extensions/DoctrineConnectionFetchDynamicReturnTypeExtension.php#L48-L74

**Comment by staabm** [comment]
just installed packagist locally and did some debugging.

the reason for this query not beeing analyzable is the following mysql error:

![grafik](https://user-images.githubusercontent.com/120441/152534176-4a34ec4b-9d16-4dee-9302-6691a9e297fa.png)

phpstan-dba simulates a value which does not fit to the mysql native type and therefore we produce a sql error

**Comment by staabm** [comment]
I think we can consider this issue fixed.

**Comment by Seldaek** [comment]
Thanks!
