### ISSUE TITLE
Support for COUNT

### ISSUE THREAD

**Issue by Seldaek** [staabm/phpstan-dba#238]
Another one:

```
        $sql = 'SELECT COUNT(*) count FROM package p WHERE p.suspect IS NOT NULL AND (p.replacementPackage IS NULL OR p.replacementPackage != "spam/spam")';

        return (int) $this->getEntityManager()->getConnection()->fetchOne($sql);
```

triggers `Cannot cast mixed to int`

From https://github.com/composer/packagist/blob/bb486fc455c7c59544dd23d7508fcdf0fcc02023/src/Entity/PackageRepository.php#L467-L469

Seems to me like count is a clear case of returning int, but maybe I missed something :)

Seems like support should work as per https://github.com/staabm/phpstan-dba/blob/5227c735a826b11d0b233387b6288f1e40a2da45/tests/default/data/pdo.php#L155-L160 but somehow it doesn't here. Not sure why.

**Comment by staabm** [comment]
> Seems to me like count is a clear case of returning int, but maybe I missed something :)

agree. at best it could maybe even be inferred as a ´0|positive-int`

**Comment by staabm** [comment]
fixed the underlying problem, that no type could be inferred.

returning a `0|positive-int` is still open and would require a proper sql parser
