### ISSUE TITLE
PDO: Support setting default fetch mode

### ISSUE THREAD

**Issue by xPaw** [staabm/phpstan-dba#253]
It is possible to configure the default fetch mode in PDO:

```php
new PDO(..., [
  PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
]);
```

It would be similar to setting errorMode on RuntimeConfiguration.

**Comment by staabm** [comment]
Could you give a full example how could beeing analyzed would look like when using this feature?

**Comment by xPaw** [comment]
The new issue you created would be the same example.

```php
<?php
$dbh = new PDO(..., [PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_NUM]);

$stmt = $dbh->query('SELECT name, colour, calories FROM fruit');
foreach ($stmt as $row) {
    print $row[0] . "\t" . $row[1] . "\t" . $row[2] . "\n";
}
```

**Comment by staabm** [comment]
Thx. A new runtime configuration option would be a perfect fit.

are you willing to contribute?

**Comment by xPaw** [comment]
I'll take a look.
