### ISSUE TITLE
tests: extract database access credentials into dot-env files

### ISSUE THREAD

**Issue by staabm** [staabm/phpstan-dba#267]
instead of duplicating the db access information across all `bootstrap.php` files in the testsuites we should have 2 dot-env files - one for the local env and one for the github actions.

that way other devs can run the testsuite locally with different db access credentials more easily

**Comment by xPaw** [comment]
There's also another unrelated issue with tests as I'm on Windows, and mariadb forces lowercase table names due to case insensitive file system.

Thus one of the tests fails:
```
-41: Query error: Table 'phpstan_dba.unknownTable' doesn't exist (1146).
+41: Query error: Table 'phpstan_dba.unknowntable' doesn't exist (1146).
```

**Comment by staabm** [comment]
> There's also another unrelated issue with tests as I'm on Windows, and mariadb forces lowercase table names due to case insensitive file system.

thx for noticing. I think it would make sense to add a windows CI job then.

if possible, we could strtolower() the db table name from my side if possible.

**Comment by staabm** [comment]
also note: we the refactoring from yesterday the db access credentials have been concentrated into https://github.com/staabm/phpstan-dba/blob/main/tests/ReflectorFactory.php

**Comment by xPaw** [comment]
There's still credentials in bootstrap.php fyi

**Comment by staabm** [comment]
> There's still credentials in bootstrap.php fyi

good point, we should fix that
