### ISSUE TITLE
Support table aliases in PdoQueryReflector

### ISSUE THREAD

**Issue by staabm** [staabm/phpstan-dba#279]
Atm table aliases only work with the MysqliQueryReflector

see 
![grafik](https://user-images.githubusercontent.com/120441/153636484-ec182c05-f50b-4611-a4a3-6fd79967530b.png)

![grafik](https://user-images.githubusercontent.com/120441/153727761-230f3809-3c38-4945-aed1-8b1b28f2b2d6.png)

**Comment by p4veI** [comment]
Hey, I was thinking I would explore some options regarding this issue, but I'm not sure what's the status of implementing some base of an sql parser - I've checked some comments in https://github.com/staabm/phpstan-dba/pull/313 and I'm not sure if I should wait for some base implementation or to go ahead with this using phpmyadmin sql parser or just go ahead with something else? wdyt?

thx

**Comment by staabm** [comment]
Hey. 

I am not having concrete plans yet. 

I would agree with anything which is not huge and works the same way on mysql/mysqli/pgsql without ugly hacks

**Comment by staabm** [comment]
you may consider using https://github.com/SQLFTW/sqlftw as a parser

**Comment by staabm** [comment]
@p4veI in https://github.com/staabm/phpstan-dba/pull/505 landed the initial implementation/integration of a sql parser
