### ISSUE TITLE
`fetchAll(PDO::FETCH_KEY_PAIR)` has incorrect return type with an extra array

### ISSUE THREAD

**Issue by xPaw** [staabm/phpstan-dba#305]
Added in: https://github.com/staabm/phpstan-dba/commit/1e28adc9bb06fe975287c2ba8248d9cca5ea1339

It's currently `array<int, array<string, int<0, 4294967295>>>` but it should be `array<string, int<0, 4294967295>>`  without the outer array.

Basically what it's doing is taking first column as the key, and second column as the value.

**Comment by staabm** [comment]
Could you post a example where it does not work as expected...?


I had another look and it seems correct as-is to me

**Comment by xPaw** [comment]
```php
$stmt = $pdo->prepare('SELECT email, adaid FROM ada');
$all = $stmt->fetchAll(PDO::FETCH_KEY_PAIR);
assertType('array<string, int<0, 4294967295>>', $all);

var_dump($all['test@example.com']); // 10
```
