### ISSUE TITLE
Error when named parameter starts with the name of another named parameter

### ISSUE THREAD

**Issue by keulinho** [staabm/phpstan-dba#361]
## Error description
There seems to be an error when resolving named parameters in queries if the parameter name starts with the name of another named parameter.

## Example query
```SQL
SELECT `id`
FROM `table`
WHERE `column` = :param OR `column` = :parameter
```
Note that the **:param**eter param name starts with the exact name of the first named parameter.

 ## Possible cause
 It seems that somewhere the occurences of the first placeholder are replaced by the bound value to that parameter, but it will also replace the first part (`:param`) of the second named parameter inside the query which leads to invalid SQL.

**Comment by staabm** [comment]
Thx for reporting. 

Would you be able to provide a failling unit test?

Just create a new file into

https://github.com/staabm/phpstan-dba/tree/main/tests/default/data

And include it from the DbaInferenceTest like others already included
