### ISSUE TITLE
PHP 8.1, PDO, MySQL, Decimal column

### ISSUE THREAD

**Issue by marmichalski** [staabm/phpstan-dba#428]
Hello,

`decimal` type is returned as `string` in PHP, but phpstan-dba thinks it's a float :cry:.

This is, of course, without stringified fetches.

(unless I miss something :scream:)

**Comment by staabm** [comment]
Thx for reporting. Are you willing to contribute?

the relevant parts can be found here
- type mappings: https://github.com/staabm/phpstan-dba/tree/5c112b0f38ff9fda55a2366c31648cbdc46283dd/src/TypeMapping
- tests https://github.com/staabm/phpstan-dba/blob/5c112b0f38ff9fda55a2366c31648cbdc46283dd/tests/default/data/pdo-mysql.php#L21

**Comment by marmichalski** [comment]
> Thx for reporting. Are you willing to contribute?

Yes, of course, but probably next week :see_no_evil:
