### ISSUE TITLE
COALESCE: returns `int|null` even if one argument is not nullable

### ISSUE THREAD

**Issue by glaubinix** [staabm/phpstan-dba#460]
I am not quite sure if or how this is fixable but if `COALESCE` is called with multiple arguments and one of them is not nullable then the value should also not be nullable.

Example: 

Table:
```
CREATE TABLE ak (
    akid int NOT NULL DEFAULT 0,
    eladaid int DEFAULT NULL,
    eadavk decimal(12,2) NOT NULL
);
```

Query:
```
SELECT COALESCE(eladaid, akid) as id FROM ak
```

I would expect that the value for `id` is always `int`

**Comment by staabm** [comment]
This requires an sql-AST which we don't yet have .. but who knows ;-)

**Comment by staabm** [comment]
@glaubinix please try the latest release. SQL Ast type narrowing is a opt-in feature right now, enabled via `RuntimeConfiguration`. 

Please give it a try

**Comment by glaubinix** [comment]
Thanks, will give this a try next week!

**Comment by glaubinix** [comment]
Apologies for not getting back to you earlier. I just tried this in our code base. Unfortunately, we are using PostgreSQL and it looks like `sqlftw/sqlftw` only supports MySQL so far. This currently fails with several internal errors like `Internal error: Unable to resolve column TIME in file` in `ParserInference::narrowResultType` line 91.

**Comment by staabm** [comment]
thanks for the feedback. I added a new todo item for supporting AST in postgres.
https://github.com/staabm/phpstan-dba/issues/538

for now we will explore the AST features in mysql only, until `sqlftw/sqlftw` stabilizes and natively supports postgres.
