### ISSUE TITLE
Support for checking update/insert/delete statemenet

### ISSUE THREAD

**Issue by jakubvojacek** [staabm/phpstan-dba#472]
Hello

in my dibi fork, I was able to successfully test update/delete/insert statements (inside a transaction). @staabm commented it out as not supported yet (https://github.com/staabm/phpstan-dba/pull/468).

Could it be supported since it worked fine in my fork? We'd have to make sure we disallow any statement that does work inside the transaction (eg put whitelist only to select, insert, update, delete to disallow truncate, alter etc)

Thanks

**Comment by staabm** [comment]
since we are running in transactios for a few releases without further problem, I am fine with enabling writable queries.

we should make sure though, that we have enough test coverage (also for other extensions, not just dibi)

**Comment by staabm** [comment]
Just to make sure we are on the same page. This feature request is about syntax validation, not about type inference?

**Comment by jakubvojacek** [comment]
> This feature request is about syntax validation,

yes, I plan to work on it next week most likely

**Comment by hemberger** [comment]
Hi! Sorry to intrude, but I was wondering if there are plans to support convenience wrapper methods once this work is completed, such as the `update()`, `insert()`, and `delete()` methods of `Doctrine\DBAL\Connection`. I saw a discussion about `QueryBuilder` in https://github.com/staabm/phpstan-dba/issues/94, but it seems like these methods might be significantly more straightforward.

Thanks for all your work on this. It's quite exciting!

**Comment by staabm** [comment]
please open a separate issue with a concrete code example and your expectations.

**Comment by staabm** [comment]
implemented with https://github.com/staabm/phpstan-dba/pull/483

**Comment by staabm** [comment]
@hemberger @jakubvojacek released with https://github.com/staabm/phpstan-dba/releases/tag/0.2.55

the feature is opt-in and should work for all supported apis (mysqli, doctrine, dibi, pdo) and all supported backends (mysql, mariadb, pgsql)

please give it a try and report back

**Comment by jakubvojacek** [comment]
Works like a charm, it actualyl found one issue with one insert query that I wasnt aware of :+1:
