### ISSUE TITLE
remove rector dependency and use symplify/astral instead

### ISSUE THREAD

**Issue by staabm** [staabm/phpstan-dba#51]
depends on https://github.com/symplify/symplify/pull/3876

**Comment by craigfrancis** [comment]
Just to note, a basic install with composer currently gets:

    Internal error: Class "Symplify\Astral\ValueObject\AttributeKey" not found

When using PdoStatementReflection (e.g. `$statement->execute(['my_field' => 123])`).

This can be temporarily fixed with:

    composer require --dev Symplify/Astral

Which installs an additional 25 packages.

**Comment by staabm** [comment]
@craigfrancis thx for the hint, fixed in https://github.com/staabm/phpstan-dba/pull/72
