### ISSUE TITLE
Inconsistency for string in query check between Record and Replay

### ISSUE THREAD

**Issue by netzhuffle** [staabm/phpstan-dba#552]
If I use a database connection, I’m (expectedly) getting errors when a string variable is directly used in a query.

However a check through Replay without database connection ignores these issues.

This is a problem when PHPStan is checked on a CI server without database as firstly doesn’t check for this issue and secondly it doesn’t play well with PHPStans baseline feature: Creating a baseline with database connection puts the error into the baseline, which then makes CI fail, as it gives an error when the ignored error is not occurring.

**Comment by staabm** [comment]
Thanks for reporting. 

In CI of this repo we ran recording and replay tasks (without a db connection) which shows errors are reported as expected. 


Could you create a small repository which shows your exact problem, so we can investigate?

**Comment by netzhuffle** [comment]
Sure! Made a minimal self contained repository at https://github.com/netzhuffle/phpstandba-replay-inconsistency.

Running with DB container up reports the string used in the query as expected.

Running with DB container down unexpectedly reports no errors.

**Comment by netzhuffle** [comment]
Oh, wait, it’s the difference in the debugMode setting of course.

Got it!

**Comment by staabm** [comment]
feel free to report new issues in case you stumble over other problems or have further feedback
