### ISSUE TITLE
AST: inconsistent behavior with functions and aliases

### ISSUE THREAD

**Issue by hemberger** [staabm/phpstan-dba#578]
There is the following test in `sql-ast-narrowing.php`:
```php
$stmt = $pdo->query('SELECT avg(freigabe1u1) as avg from ada');
assertType('PDOStatement<array{avg: int<-128, 127>, 0: int<-128, 127>}>', $stmt);
```
If I remove the alias, then I get a different (and inconsistent) type:
```php
$stmt = $pdo->query('SELECT avg(freigabe1u1) from ada');
assertType('PDOStatement<array{avg(freigabe1u1): numeric-string|null, 0: int<-128, 127>}>', $stmt);
```
It looks like the only place it is correct is the associative parameter in the unaliased query, where it gets `avg(freigabe1u1): numeric-string|null` (since the result of `avg` shouldn't be an integer).

Here's another example with `min` instead of `avg`.
```php
$stmt = $pdo->query('SELECT min(freigabe1u1) as min from ada');
assertType('PDOStatement<array{min: int<-128, 127>, 0: int<-128, 127>}>', $stmt);
```
```php
$stmt = $pdo->query('SELECT min(freigabe1u1) from ada');
assertType('PDOStatement<array{min(freigabe1u1): int<-32768, 32767>|null, 0: int<-128, 127>}>', $stmt);
```
Again, only `min(freigabe1u1): int<-32768, 32767>|null` is correct, because the field is a SMALLINT, not a TINYINT.

I've spot checked a few of the numeric functions, and so far they have all exhibited this behavior (avg, min, max, sum, round, abs).

**Comment by staabm** [comment]
I think this is the same problem as https://github.com/staabm/phpstan-dba/pull/570

**Comment by staabm** [comment]
@hemberger this one can be closed now?

**Comment by hemberger** [comment]
> @hemberger this one can be closed now?

I think all the alias and integer issues have been resolved, but there is still an issue with `AVG` (it should not be restricted to integers). Do you want me to close this and report that separately?
