### ISSUE TITLE
Analyzing multiple connections

### ISSUE THREAD

**Issue by aszenz** [staabm/phpstan-dba#585]
We use two db connections in the app, is their a way to analyze them both, i only see an option to add one pdo mysql db

**Comment by staabm** [comment]
You can use https://github.com/staabm/phpstan-dba/blob/main/src/QueryReflection/ChainedReflector.php to combine several pdo or mysql,... reflectors

**Comment by aszenz** [comment]
Perfect, works great.
I see it now in docs too https://github.com/staabm/phpstan-dba/blob/main/docs/reflectors.md, hence closing this issue

**Comment by aszenz** [comment]
How does phpstan-dba know which reflector to use for each file like a repository, i see some errors where it uses an incorrect reflector on the repository file and throws errors like table `central.foo` doesn't exist, while it should actually check `demo.foo`

**Comment by staabm** [comment]
the chain just works thru the list of reflectors. the first one which returns a type, is used:

https://github.com/staabm/phpstan-dba/blob/31c4de9e3ea64110903e2d892ea0e8e26726afe9/src/QueryReflection/ChainedReflector.php#L54-L60

**Comment by aszenz** [comment]
Hmm, my query should work on only one reflector, but it's not using that reflector

**Comment by staabm** [comment]
please open a new issue with code which reproduces your problem.

it might be useful to create a small example repo
