### ISSUE TITLE
generic type mysqli_result error with phpstan v1.10.36 and v1.10.37

### ISSUE THREAD

**Issue by slackero** [staabm/phpstan-dba#631]
Trying to update phpstan to v1.10.37 results in an error.

```
--------------------------------------------------------------------------------
  vendor/staabm/phpstan-dba/config/Mysqli.stub:29
 --------------------------------------------------------------------------------
 PHPDoc tag @param for parameter $result contains generic type mysqli_result<mixed> but class mysqli_result is not generic.
 --------------------------------------------------------------------------------
```

 It doesn't help to ignore the error or exclude the path.

Up to phpstan  v1.10.35 it works without this error message. Maybe it is related to this pull request — [mysqli] Add stubs for mysqli and mysqli_result classes phpstan/phpstan-src#2295.

**Comment by staabm** [comment]
thanks for reporting. I have also seen this error and it seems phpstan-dba is not compatible with the latest phpstan releases because of this stubs error.

I will work on a fix when time allows, as my own projects are also hit by this problem.

**Comment by staabm** [comment]
in https://github.com/staabm/phpstan-dba/releases/tag/0.2.79 I have pushed a new release containing a bugfix for that particular problem to make phpstan-dba work for everyone not using `mysqli_fetch_object `.

in the next step I will have a look to get all features back, but at least the more ciritical stuff should work again
