### ISSUE TITLE
Question regarding sqlftw/sqlftw dependency

### ISSUE THREAD

**Issue by glaubinix** [staabm/phpstan-dba#689]
Commit https://github.com/staabm/phpstan-dba/commit/b0d10ac70a99026cdc6d93948812077c6761350f introduces [sqlftw/sqlftw](https://packagist.org/packages/sqlftw/sqlftw) as a dependency whereas before that dependency was optional. The package still indicates a proprietary license, which as far as I can tell [hasn't been decided by the maintainer](https://github.com/SQLFTW/sqlftw/issues/25). Just wondering if this change was intentional?

**Comment by staabm** [comment]
thanks for noting. it was indeed not intentional.

**Comment by staabm** [comment]
pushed a new release with a fix

**Comment by glaubinix** [comment]
thank you!
