### ISSUE TITLE
list-like arrays should be lists

### ISSUE THREAD

**Issue by Seldaek** [staabm/phpstan-dba#719]
I have this code in packagist (DownloadManager.php line 215):

```
        $versionIds = $this->getEM()->getConnection()->fetchFirstColumn(
            'SELECT id FROM package_version WHERE id IN (:ids)',
            ['ids' => array_keys($versionsWithDownloads)],
            ['ids' => ArrayParameterType::INTEGER]
        );
        \PHPStan\dumpType($versionIds);
```

which outputs:
```
Dumped type: array<int<0, max>, int<0, 4294967295>>
```

This was fine with phpstan 1.x but with 2.x it now complains about lists, so this started failing as I pass it into a list-requiring argument.

I believe it would be safe to convert these to lists, and I think it's phpstan-dba that is responsible for this and not phpstan-doctrine, but I hope I'm not bugging the wrong person :)

**Comment by staabm** [comment]
fix in https://github.com/staabm/phpstan-dba/releases/tag/0.3.1

**Comment by Seldaek** [comment]
Oh no too late I'm away from the laptop now ;) Just kidding thanks for the super quick fix! Will try it out tomorrow.

**Comment by Seldaek** [comment]
Works great, thanks!
